### ISSUE TITLE
TuningInstance design issue

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3tuning#169]
the TuningInstance itself seems pretty good IMHO.

it encodes nicely the "problem" the tuner has to solve, and defines it objective function.

what i dislike a bit (?) / wonder about is the resampling.

isnt this something the tuner should decide for itself?

eg how many iterations it performs for an individual configuration?
see racing and hyperband.

inb mlr we always solved this by setting then the resampling to holdout and saying the tuner can then decide to do multiple evals on a point if it wants to?

writing this down it does not seem so bad what we have? 

@mllg

?

**Comment by be-marc** [comment]
`resampling` is a parameter of `$eval_many()` now so that the `Tuner` can change the resampling. This is implemented through the `constants` field in [`bbotk`](https://github.com/mlr-org/bbotk/blob/main/R/Objective.R).  See [`TunerIrace`](https://github.com/mlr-org/mlr3tuning/blob/main/R/TunerIrace.R) and [`ObjectiveTuning`](https://github.com/mlr-org/mlr3tuning/blob/main/R/ObjectiveTuning.R) for a working implementation.
