### ISSUE TITLE
Logging tuning results to file

### ISSUE THREAD

**Issue by pawelkasperkiewicz** [mlr-org/mlr3tuning#189]
Hi,

my idea is to add feature to every tuning method which will allows us to logging evaluated configurations to file. This method is available in mlrMBO package.
I often have situations where I lost many evaluated sets of parameters due to hardware problems or  just when I must stop computations.
Now I must write long functions for combine mlrMBO with mlr3tuning what cost some time.

**Comment by berndbischl** [comment]
hi @pawelkasperkiewicz 
ok, i can certainly see the need for that. could you outline a bit how this should look like? 
currently, please note that you have the following option:

a) the mlr3 logger already logs all evals to the console. this can easily be directed to a file. but it's not really parseable in an easy fashion at the end
b) the TuningInstance logs all evals into a datatable. but this will potentially not be there anymore when an error occurs.

would it be ok to simply enhance b) with an option that the Tuninginstance saves itself to an RDS file on disk? than the complete state is available there.

please note that if we do that, you cannot easily warmstart each tuner with that state, because that depends on the algorithm / the implementation having an option for this

also i would like to have an mlr3 compatible version of mlrmbo very soon, currenly that is a mess because mlrmlbo depends on mlr2. but thats a bit of more work.

**Comment by pawelkasperkiewicz** [comment]
a) I forget about that, logging output can be helpful, but it isn't tidy solution.

Saves data.table file will be ok, but better solution can be saves benchmark object or TuningInstance to RDS file, what allows us to combine couple of files from different runs into one benchmark and then use dedicated tools to analyze it.

> please note that if we do that, you cannot easily warmstart each tuner with that state, because that depends on the algorithm / the implementation having an option for this

I am aware of this. I don't use this option in mlrMBO too because it makes imposible to change some settings in algorithm, so I always use saved configurations like design to mlrMBO with computed y column.

> also i would like to have an mlr3 compatible version of mlrmbo very soon, currenly that is a mess because mlrmlbo depends on mlr2. but thats a bit of more work.

I am waiting for tidy bayesian optimization in mlr3 but I am currently using mlr3 to kaggle competition so I combined TuningInstance with mlrMBO.



I think arguments to saving function can be add to TuningInstance object. For example:

`TuningInstance$save_results <- list(path = "xxx.RDS", freq = 1L)`

where freq arg is frequency of saving results related to number of iterations of tuning algorithm.

**Comment by be-marc** [comment]
Save to disk is possible with callbacks now. See https://mlr3tuning.mlr-org.com/reference/mlr3tuning.backup.html and https://bbotk.mlr-org.com/reference/bbotk.backup.html.
