### ISSUE TITLE
Support "early stopping"

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3tuning#216]
Popular issue from {mlr}: https://github.com/mlr-org/mlr/issues/1398

Active issue in {mlr3}?: https://github.com/mlr-org/mlr3/issues/272

There was a [SO question](https://stackoverflow.com/questions/59385260/mlr-equivalent-of-carets-model-selectionfunction-in-r) asking whether other approaches for optimizing hyperpars than evaluating on a measure are possible, i.e. something like caret::oneSE() does: https://www.rdocumentation.org/packages/caret/versions/6.0-84/topics/oneSE

This fun lets the user choose between
• a measure
• oneSE (by Breiman)
• tolerance

**Comment by kapsner** [comment]
I've spent some thoughts on this topic when creating the [mlr3learners.lightgbm](https://github.com/mlr3learners/mlr3learners.lightgbm) package that I'd like to share here.

At first, I've implemented only the [lgb.train](https://lightgbm.readthedocs.io/en/latest/R/reference/lgb.train.html) function and tried to tune the parameter ''num_iterations" using the `mlr3tuning` package just to realize that this parameter is ignored by lightgbm and instead the argument "nrounds" has to be specified in the function (see also https://github.com/Microsoft/LightGBM/issues/343).

Therefore, I implemented the following in mlr3learners.lightgbm's [backend](https://github.com/mlr3learners/mlr3learners.lightgbm/blob/master/R/LightGBM.R) to pass 'num_iterations' to 'nrounds', if defined by the user.

```r
# check for user-changed num_iterations here
if (!is.null(self$param_set$values[["num_iterations"]])) {
    # if yes, pass value to nrounds
    self$nrounds <- self$param_set$values[["num_iterations"]]
}
```

This made it possible, to tune 'num_iterations' using the autotuner-instance. Also mlr3tunings parallelization is used by setting the lightgbm parameter 'num_threads = 1L' and using the future-backend (as suggested [here](https://mlr3book.mlr-org.com/parallelization.html)). 

```r
learner <- mlr3::lrn("classif.lightgbm")

# switch off lightgbm's internal CV
learner$lgb_learner$nrounds_by_cv <- FALSE

# define parameters
learner$param_set$values <- list(
  "objective" = "binary",
  "learning_rate" = 0.1,
  "seed" = 17L,
  "bagging_freq" = 5L,
  "num_threads" = 1L,
  "metric" = "auc"
)

# define num_iterations as tuning parameter
tune_ps <- ParamSet$new(list(
  ParamDbl$new("num_iterations", lower = 1L, upper = 200L)
))

# design_points
design <- paradox::generate_design_grid(
  tune_ps,
  param_resolutions = c(
    num_iterations = 200
))

# Create the resampling strategy and the measure
resampling <- mlr3::rsmp("cv", folds = 5)
measure <- mlr3::msr("classif.auc")

# Create the tuner 
tuner <- mlr3tuning::tnr("design_points", design = design$data, batch_size = 1)

# Create the terminator 
terminator <- mlr3tuning::term("stagnation", iters = 10)

# Instantiate the AutoTuner instance 
at <- mlr3tuning::AutoTuner$new(
  learner = learner,
  resampling = resampling,
  measures = measure,
  tune_ps = tune_ps,
  terminator = terminator,
  tuner = tuner
)
at
#> <AutoTuner:classif.lightgbm.tuned>
#> * Model: -
#> * Parameters: objective=binary, learning_rate=0.1, seed=17,
#>   bagging_freq=5, num_threads=1, metric=auc
#> * Packages: lightgbm
#> * Predict Type: prob
#> * Feature types: numeric, factor, character, integer
#> * Properties: importance, missings, multiclass, twoclass

# Train the tuner 
future::plan("multisession")
set.seed(17)

system.time(
  at$train(task, row_ids = split$train_index)
)
#> INFO  [08:04:20.059] Starting to tune 1 parameters with '<TunerDesignPoints>' and '<TerminatorStagnation>' 
#> INFO  [08:04:20.091] Terminator settings: iters=10, threshold=0 
#> INFO  [08:04:20.113] Evaluating 1 configurations 
#> INFO  [08:04:20.116]  num_iterations 
#> INFO  [08:04:20.116]               1 
#> INFO  [08:04:20.180] Benchmark with 5 resampling iterations 
#> INFO  [08:04:20.643] Applying learner 'classif.lightgbm' on task 'pima' (iter 1/5) 
#> INFO  [08:04:21.162] Applying learner 'classif.lightgbm' on task 'pima' (iter 5/5) 
#> INFO  [08:04:21.624] Applying learner 'classif.lightgbm' on task 'pima' (iter 3/5) 
#> INFO  [08:04:22.127] Applying learner 'classif.lightgbm' on task 'pima' (iter 2/5) 
#> INFO  [08:04:22.142] Applying learner 'classif.lightgbm' on task 'pima' (iter 4/5) 
[.............]
[.............]
[.............]
[.............]
#> INFO  [08:05:11.731] Finished tuning after 32 evals
#>    user  system elapsed 
#>  31.067   1.142  52.012
future::plan("sequential")

at$learner$model$current_iter()
#> [1] 22
```

However, this approach took much longer than I expected from my experiences when using the [lgb.cv](https://lightgbm.readthedocs.io/en/latest/R/reference/lgb.cv.html) function for finding the optimal 'nrounds' by using the original implementation's 'early_stopping_rounds' argument. 

In order to be able to use lightgbm's internal CV from mlr3, I implemented the `lgb.cv` function as method upstream to the calling of the `lgb.train` function. This is demonstrated in the following example, using the same settings as above (terminator stagnation --> 'early_stopping_rounds = 10' and 'nrounds = 200').

```r
learner <- mlr3::lrn("classif.lightgbm")
learner$early_stopping_rounds <- 10
learner$nrounds <- 200

# define parameters
learner$param_set$values <- list(
  "objective" = "binary",
  "learning_rate" = 0.1,
  "seed" = 17L,
  "bagging_freq" = 5L,
  "metric" = "auc"
)

system.time(
  learner$train(task, row_ids = split$train_index)
)
#> [1]: valid's auc:0.784945+0.0394604 
#> [21]:    valid's auc:0.809+0.032853
#>    user  system elapsed 
#>   2.847   0.038   1.296

learner$model$current_iter()
#> [1] 29
```

This is much faster compared to using the mlr3tuning approach. Please also note, that here lightgbm's native parallelization is used by 'not setting' the 'num_threads' parameter, using its default value. Furthermore, the results of both approaches seem to differ (22 vs. 29 rounds) (which is likely due to different samplings during the CVs).

In `mlr3learners.lightgbm`, the upstream CV is switched on by default for finding the optimal 'nrounds' using a 5-fold CV. The optimal 'nrounds' argument is then in a second step used to train the final model. 

However, the upstream CV can also be configured by changing the number of folds or even be switched off:

```r
# set CV folds:
learner$lgb_learner$cv_folds <- 10L

# switch off lightgbm's internal CV
learner$lgb_learner$nrounds_by_cv <- FALSE
```

From these experiences, I would recommend to not only implement a generic early-stopping with the mlr3tuning package, but also support the learner's native implementations (as also suggested [here](https://github.com/mlr-org/mlr/issues/1398#issuecomment-283260149)).

The code for the mlr3learners.lightgbm-implementation might not be pretty, however, it should be not too laborious to adapt the concepts of its `train_cv` method to e.g. xgboost due to the similar APIs of lightgbm and xgboost.

If this is of interest, I could also invest some time to implement the [xgb.cv](https://www.rdocumentation.org/packages/xgboost/versions/0.90.0.2/topics/xgb.cv) function into the https://github.com/mlr-org/mlr3learners in the above described manner.

**Comment by latenighthacks** [comment]
@kapsner Personally, I am very interested in an xgb.cv implementation that includes early_stopping_rounds. I would love to see this in mlr3 so I could leverage the latest approaches to ML in R without having to write XGBoost code by hand.

My understanding is that Caret and Scikit-Learn have supported the use of early_stopping_rounds for several years, now.

**Comment by ThomasWolf0701** [comment]
Any news on that ? Would be great if this could be supported.

**Comment by ThomasWolf0701** [comment]
> 
> 
> I've spent some thoughts on this topic when creating the [mlr3learners.lightgbm](https://github.com/mlr3learners/mlr3learners.lightgbm) package that I'd like to share here.
> 
> At first, I've implemented only the [lgb.train](https://lightgbm.readthedocs.io/en/latest/R/reference/lgb.train.html) function and tried to tune the parameter ''num_iterations" using the `mlr3tuning` package just to realize that this parameter is ignored by lightgbm and instead the argument "nrounds" has to be specified in the function (see also [microsoft/LightGBM#343](https://github.com/microsoft/LightGBM/issues/343)).
> 
> Therefore, I implemented the following in mlr3learners.lightgbm's [backend](https://github.com/mlr3learners/mlr3learners.lightgbm/blob/master/R/LightGBM.R) to pass 'num_iterations' to 'nrounds', if defined by the user.
> 
> ```r
> # check for user-changed num_iterations here
> if (!is.null(self$param_set$values[["num_iterations"]])) {
>     # if yes, pass value to nrounds
>     self$nrounds <- self$param_set$values[["num_iterations"]]
> }
> ```
> 
> This made it possible, to tune 'num_iterations' using the autotuner-instance. Also mlr3tunings parallelization is used by setting the lightgbm parameter 'num_threads = 1L' and using the future-backend (as suggested [here](https://mlr3book.mlr-org.com/parallelization.html)).
> 
> ```r
> learner <- mlr3::lrn("classif.lightgbm")
> 
> # switch off lightgbm's internal CV
> learner$lgb_learner$nrounds_by_cv <- FALSE
> 
> # define parameters
> learner$param_set$values <- list(
>   "objective" = "binary",
>   "learning_rate" = 0.1,
>   "seed" = 17L,
>   "bagging_freq" = 5L,
>   "num_threads" = 1L,
>   "metric" = "auc"
> )
> 
> # define num_iterations as tuning parameter
> tune_ps <- ParamSet$new(list(
>   ParamDbl$new("num_iterations", lower = 1L, upper = 200L)
> ))
> 
> # design_points
> design <- paradox::generate_design_grid(
>   tune_ps,
>   param_resolutions = c(
>     num_iterations = 200
> ))
> 
> # Create the resampling strategy and the measure
> resampling <- mlr3::rsmp("cv", folds = 5)
> measure <- mlr3::msr("classif.auc")
> 
> # Create the tuner 
> tuner <- mlr3tuning::tnr("design_points", design = design$data, batch_size = 1)
> 
> # Create the terminator 
> terminator <- mlr3tuning::term("stagnation", iters = 10)
> 
> # Instantiate the AutoTuner instance 
> at <- mlr3tuning::AutoTuner$new(
>   learner = learner,
>   resampling = resampling,
>   measures = measure,
>   tune_ps = tune_ps,
>   terminator = terminator,
>   tuner = tuner
> )
> at
> #> <AutoTuner:classif.lightgbm.tuned>
> #> * Model: -
> #> * Parameters: objective=binary, learning_rate=0.1, seed=17,
> #>   bagging_freq=5, num_threads=1, metric=auc
> #> * Packages: lightgbm
> #> * Predict Type: prob
> #> * Feature types: numeric, factor, character, integer
> #> * Properties: importance, missings, multiclass, twoclass
> 
> # Train the tuner 
> future::plan("multisession")
> set.seed(17)
> 
> system.time(
>   at$train(task, row_ids = split$train_index)
> )
> #> INFO  [08:04:20.059] Starting to tune 1 parameters with '<TunerDesignPoints>' and '<TerminatorStagnation>' 
> #> INFO  [08:04:20.091] Terminator settings: iters=10, threshold=0 
> #> INFO  [08:04:20.113] Evaluating 1 configurations 
> #> INFO  [08:04:20.116]  num_iterations 
> #> INFO  [08:04:20.116]               1 
> #> INFO  [08:04:20.180] Benchmark with 5 resampling iterations 
> #> INFO  [08:04:20.643] Applying learner 'classif.lightgbm' on task 'pima' (iter 1/5) 
> #> INFO  [08:04:21.162] Applying learner 'classif.lightgbm' on task 'pima' (iter 5/5) 
> #> INFO  [08:04:21.624] Applying learner 'classif.lightgbm' on task 'pima' (iter 3/5) 
> #> INFO  [08:04:22.127] Applying learner 'classif.lightgbm' on task 'pima' (iter 2/5) 
> #> INFO  [08:04:22.142] Applying learner 'classif.lightgbm' on task 'pima' (iter 4/5) 
> [.............]
> [.............]
> [.............]
> [.............]
> #> INFO  [08:05:11.731] Finished tuning after 32 evals
> #>    user  system elapsed 
> #>  31.067   1.142  52.012
> future::plan("sequential")
> 
> at$learner$model$current_iter()
> #> [1] 22
> ```
> 
> However, this approach took much longer than I expected from my experiences when using the [lgb.cv](https://lightgbm.readthedocs.io/en/latest/R/reference/lgb.cv.html) function for finding the optimal 'nrounds' by using the original implementation's 'early_stopping_rounds' argument.
> 
> In order to be able to use lightgbm's internal CV from mlr3, I implemented the `lgb.cv` function as method upstream to the calling of the `lgb.train` function. This is demonstrated in the following example, using the same settings as above (terminator stagnation --> 'early_stopping_rounds = 10' and 'nrounds = 200').
> 
> ```r
> learner <- mlr3::lrn("classif.lightgbm")
> learner$early_stopping_rounds <- 10
> learner$nrounds <- 200
> 
> # define parameters
> learner$param_set$values <- list(
>   "objective" = "binary",
>   "learning_rate" = 0.1,
>   "seed" = 17L,
>   "bagging_freq" = 5L,
>   "metric" = "auc"
> )
> 
> system.time(
>   learner$train(task, row_ids = split$train_index)
> )
> #> [1]: valid's auc:0.784945+0.0394604 
> #> [21]:    valid's auc:0.809+0.032853
> #>    user  system elapsed 
> #>   2.847   0.038   1.296
> 
> learner$model$current_iter()
> #> [1] 29
> ```
> 
> This is much faster compared to using the mlr3tuning approach. Please also note, that here lightgbm's native parallelization is used by 'not setting' the 'num_threads' parameter, using its default value. Furthermore, the results of both approaches seem to differ (22 vs. 29 rounds) (which is likely due to different samplings during the CVs).
> 
> In `mlr3learners.lightgbm`, the upstream CV is switched on by default for finding the optimal 'nrounds' using a 5-fold CV. The optimal 'nrounds' argument is then in a second step used to train the final model.
> 
> However, the upstream CV can also be configured by changing the number of folds or even be switched off:
> 
> ```r
> # set CV folds:
> learner$lgb_learner$cv_folds <- 10L
> 
> # switch off lightgbm's internal CV
> learner$lgb_learner$nrounds_by_cv <- FALSE
> ```
> 
> From these experiences, I would recommend to not only implement a generic early-stopping with the mlr3tuning package, but also support the learner's native implementations (as also suggested [here](https://github.com/mlr-org/mlr/issues/1398#issuecomment-283260149)).
> 
> The code for the mlr3learners.lightgbm-implementation might not be pretty, however, it should be not too laborious to adapt the concepts of its `train_cv` method to e.g. xgboost due to the similar APIs of lightgbm and xgboost.
> 
> If this is of interest, I could also invest some time to implement the [xgb.cv](https://www.rdocumentation.org/packages/xgboost/versions/0.90.0.2/topics/xgb.cv) function into the https://github.com/mlr-org/mlr3learners in the above described manner.
> 
> (The demonstrated code is also available [here](https://github.com/mlr3learners/mlr3learners.lightgbm/blob/master/vignettes/mlr3learners_lightgbm_early_stopping.Rmd))

This is really great and helpful. The only downside is that it is not possible to have blocked/grouped cv folds.

**Comment by be-marc** [comment]
> However, this approach took much longer than I expected from my experiences when using the lgb.cv function for finding the optimal 'nrounds' by using the original implementation's 'early_stopping_rounds' argument.

This implementation is slower because the models are not continued. Early stopping in `light.gbm` halts the model building process and provides additional boosting iterations to continue the building process if the performance still increases. The implementation by kapsner starts the model building from the beginning for each proposed `n_rounds`.

We have experimental branches called `continue` in `mlr3`, `mlr3learners`, `bbotk`, `mlr3tuning` and `mlr3hyperband`. Hyperband selects promising hyperparameter configurations and continues these models in the next round. You can play around with this. It might take some time until this is merged into the packages and the API might change in the future. Currently only `classif.xgboost` is implemented but you can easily add `LightGBM`.

**Comment by be-marc** [comment]
Early Stopping is now supported. See https://mlr-org.com/gallery/optimization/2022-11-04-early-stopping-with-xgboost/
