### ISSUE TITLE
TunerDesignPoints should not convert to Design for assertions only

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3tuning#229]
When https://github.com/mlr-org/paradox/issues/268 is fixed there ought to be a dedicated function that does that.

**Comment by be-marc** [comment]
We check the design with `instance$search_space$check_dt` now. Closed by https://github.com/mlr-org/bbotk/commit/6b3b991d8f0cae3a0a5629b7a399702f6ba75a2f

@mb706 We somehow overlooked your PR https://github.com/mlr-org/paradox/pull/270 and implemented `ParamSet$check_dt`. Since we just released paradox on CRAN, we might stick to `check_dt` for now. Your solution with a `check` method that takes a list or data.table might be better. I think we will just use your code or parts of it in a later release.
