### ISSUE TITLE
For what is batch_size in random search good for?

### ISSUE THREAD

**Issue by schalkdaniel** [mlr-org/mlr3tuning#31]
Is this just good for parallelization or correct stopping?

**Comment by jakob-r** [comment]
It controls how many evaluations are done in one step of the optimization

- if the termination criterion only includes evals batch_size can be equal to the number of evals
- if we have only one CPU batch_size could be always 1
- the termination criteria can only be checked after/before each batch is evaluated, therefore having a big batch size and e.g. a time dependent termination can lead to longer runtimes and more evaluations than wanted
- Setting the batch size to the number of available CPUs is also not always the best idea because if we have heterogeneous runtimes this leads to one idle times: e.g.: one job of the batch finishes after 5 seconds but the others need 20 seconds. Now the first has to wait 15s  until the batch is completed and the termination is checked

**Comment by berndbischl** [comment]
yes, but nearly all of these arguments concern parallelization, and should probably be dealt with elsewhere / on a more general level? 

e.g. we also do not have a setting  "batch_size" for resample....

the only valid argument daniel and me could find was the (early) checking for termination. and i am not really sure that's enough. OTOH we don't have to remove this simple option, but it seems a bit "weird".

@mllg

**Comment by jakob-r** [comment]
> we also do not have a setting "batch_size" for resample....

Why should we? It is only important for checking termination criteria as you correctly pointed out.

**Comment by berndbischl** [comment]
Then reread your own answer. You argued about other stuff (additionally)
